<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />
  <Sdk Name="ktsu.Sdk.App" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="ktsu.Extensions" />
    <PackageReference Include="ktsu.Semantics.Color" />
    <PackageReference Include="ktsu.Semantics.Paths" />
    <PackageReference Include="ktsu.Semantics.Strings" />
    <PackageReference Include="Polyfill" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>
</Project>
